name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Build
        run : make build
      - name : Copy
        run : make copy
      - name: Test
        run: make test
      - name : Format
        run : make format
      - name: Lint
        run: make lint
      - name: Build
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: Rust_Binary

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: downloaded-artifact