name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: build Rust
      run: make build
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Archive and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml_pipeline-artifacts
          path: ${{ github.workspace }}
        
      - name: Save to repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo GH_TOKEN: "${GH_TOKEN}"
          git config --global user.name 'github-actions'
          git config --local user.email "action@github.com"
          git add main/test/target/release/main
          git commit -m "Added Executable" || echo "ignore commit failure, proceed"
          git push 
    

  deploy:
    needs: build
    steps:
    - uses: actions/checkout@v3

    - uses: actions/upload-artifact@v3
      with:
        name: Rust Binary
        path: main/test/target/release/main
