name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Build
        run : make build
      - name: Test
        run: make test
      - name : Format
        run : make format
      - name: Lint
        run: make lint
      - name: Archive and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: ${{ github.workspace }}
        
      - name: Save to repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          make copy
          echo GH_TOKEN: "${GH_TOKEN}"
          git config --global user.name 'github-actions'
          git config --local user.email "action@github.com"
          git add RUST_Binary
          git commit -m "Added Binary" || echo "ignore commit failure, proceed"
          git push
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: Binary